Removed monorepo (#546)

diff --git a/docker/prod/Dockerfile b/docker/prod/Dockerfile
--- a/docker/prod/Dockerfile
+++ b/docker/prod/Dockerfile
@@ -23,10 +23,10 @@ RUN apt-get update
 RUN apt-get install jq
 
 # Add additional replacements for configurations below as necessary
-RUN jq -e '.cortexApi.scope|="NGINX_REPLACE_CORTEX_API_SCOPE"' ./app/src/ep.config.json > ./app/src/ep.config.json.tmp && cp ./app/src/ep.config.json.tmp ./app/src/ep.config.json
+RUN jq -e '.cortexApi.scope|="NGINX_REPLACE_CORTEX_API_SCOPE"' ./src/ep.config.json > ./src/ep.config.json.tmp && cp ./src/ep.config.json.tmp ./src/ep.config.json
 
 # Remove the temp file used for replacements since jq cannot handle in-line replacements
-RUN rm ./app/src/ep.config.json.tmp
+RUN rm ./src/ep.config.json.tmp
 
 RUN yarn build
 
@@ -34,10 +34,10 @@ RUN yarn build-components
 
 # Publish components to npm
 RUN npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
-RUN npm publish components/ || echo "Components publish failed"
+RUN npm publish src/components/ || echo "Components publish failed"
 
 FROM nginx:1.15.1
-COPY --from=builder /project/app/build/ /usr/share/nginx/www
+COPY --from=builder /project/build/ /usr/share/nginx/www
 COPY ./docker/prod/nginx.conf /etc/nginx/conf.d/default.conf.template
 
 ENV uri \$uri
