Push updated components (#533)
* Push updated components

- push updates

* - build components in package.json

* - Add webpack & cli as dependency

* - add build-components command

* add typings to tsconfig (#534)

* add typings to tsconfig

* change version in package.json and add typings to tsconfig

* Fixed types in components/package.json

* - increment package.jsson

* Updated yarn.lock

diff --git a/docker/prod/Dockerfile b/docker/prod/Dockerfile
--- a/docker/prod/Dockerfile
+++ b/docker/prod/Dockerfile
@@ -6,10 +6,6 @@ WORKDIR /project
 
 ADD ./ /project
 
-# Publish components to npm
-RUN npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
-RUN npm publish components/ || echo "Components publish failed"
-
 RUN yarn
 
 RUN echo "deb http://deb.debian.org/debian/ jessie main \n\
@@ -33,6 +29,12 @@ RUN jq -e '.cortexApi.scope|="NGINX_REPLACE_CORTEX_API_SCOPE"' ./app/src/ep.conf
 RUN rm ./app/src/ep.config.json.tmp
 
 RUN yarn build
+
+RUN yarn build-components
+
+# Publish components to npm
+RUN npm set //registry.npmjs.org/:_authToken $NPM_TOKEN
+RUN npm publish components/ || echo "Components publish failed"
 
 FROM nginx:1.15.1
 COPY --from=builder /project/app/build/ /usr/share/nginx/www
